### ISSUE TITLE
训练数据格式问题

### ISSUE THREAD

**Issue by georgewangchn** [iseesaw/FAQ-Semantic-Retrieval#1]
请问训练数据的格式能提供个文件吗，我准备按那个json的数据格式准备的，一直报错，谢谢！

**Comment by georgewangchn** [comment]
主题和post的关系是不是一对一关系，主题-和问题的关系是不是一对多的关系。
我本身的qa问答对，是不是q划分成唯一的主题，再扩充q的规模？

**Comment by iseesaw** [comment]
> 主题和post的关系是不是一对一关系，主题-和问题的关系是不是一对多的关系。
> 我本身的qa问答对，是不是q划分成唯一的主题，再扩充q的规模？

是的

> 请问训练数据的格式能提供个文件吗，我准备按那个json的数据格式准备的，一直报错，谢谢！

请问这个是运行的哪个命令，主要的 csv 数据格式是这样的
```csv
sentence1,sentence2,label
开初婚未育证明怎么弄？,初婚未育情况证明怎么开？,1
谁知道她是网络美女吗？,爱情这杯酒谁喝都会醉是什么歌,0
人和畜生的区别是什么？,人与畜生的区别是什么！,1
男孩喝女孩的尿的故事,怎样才知道是生男孩还是女孩,0
这种图片是用什么软件制作的？,这种图片制作是用什么软件呢？,1
这腰带是什么牌子,护腰带什么牌子好,0
什么牌子的空调最好！,什么牌子的空调扇最好,0
校花的贴身高手打给什么时候完结,校花的贴身高手什么时候可以写完,1
移动手机可以改成电信手机吗,能把移动手机改成电信手机吗,1
```
