### ISSUE TITLE
请问chitchat-faq-small数据集是如何生成的？

### ISSUE THREAD

**Issue by dst111dst** [iseesaw/FAQ-Semantic-Retrieval#2]
不好意思打扰了，非常感谢分享的代码，请问chitchat-faq-small是根据[https://github.com/microsoft/botframework-cli/blob/main/packages/qnamaker/docs/chit-chat-dataset.md](url)生成的吗？那`post`是如何确定的呢？感谢回答，谢谢

**Comment by iseesaw** [comment]
你好！这个是我们内部人员标注的，初始的 post 应该是结合对话机器人 log 构造的，与你链接的这个项目没有关系的。
